### PR TITLE
Add support for web scraping

### PR DESCRIPTION
**Pull request by ankrgyl**
This change adds the basics required to support scraping:

- A web.py package that wraps selenium/chromium and can extract screenshots
- Javascript code (find_leaf_nodes.js) that finds all leaf nodes with words in an HTML document. This is in JS specifically so that we can reuse it for other use cases (e.g. a Chrome plugin) where the text gets extracted client-side
- A new `WebDocument` class (+ a bit of supportive refactoring) that wraps the web driver
- Tests + documentation

### CODE REVIEW

**Comment by jagilley** [comment]
You're legendary, Impira team, was just trying to implement this functionality myself. FWIW the web scraping part LGTM

**Comment by ankrgyl** [comment]
Nice to hear! Have you taken it for a spin yet?

**Review by amazingvince — APPROVED** [review]

**Comment by jagilley** [comment]
No, haven't got the chance yet @ankrgyl

**Comment by ankrgyl** [comment]
Okay no worries @jagilley let me know when you do! Merging this in now

**Comment by jagilley** [comment]
Works great, thank you @ankrgyl!

**Pull request merged**
